### ISSUE TITLE
Add branch for Blender 2.79

### ISSUE THREAD

**Issue by Symbian9** [macio97/Real-Camera#1]
Please, add branch `2.79` for maintain add-on version for Blender 2.79x

- https://github.com/macio97/Real-Camera/tree/2.79

Also, if possible, backport here new features from & bug fixes from `master`.

**Comment by macio97** [comment]
Sorry but since i have to maintain a lot of other addons and since the version for 2.7 is stable and complete i won't update it.
Also the autoexposure feature was possible only because of the new Python API in 2.8. So definitely not an issue.
