### ISSUE TITLE
If I enable Auto Exposure, everything become pure white

### ISSUE THREAD

**Issue by Lissanro** [macio97/Real-Camera#2]
This issue is reproducible with standard cube scene with fresh default config, both in Eevee and Cycles, right after downloading the addon from https://3d-wolf.com/products/camerafolder/Real%20Camera.zip, installing and enabling it. This is first time I'm trying it, so I do not know at what Blender version it stopped working. I'm using latest 2.90 build.

**Comment by macio97** [comment]
Thank you for reporting, it seems it happens from Blender 2.83. Going to work on it now.

**Comment by Lissanro** [comment]
I just noticed that this issue happens only of Filmic look set to "None", otherwise addon does nothing at all. This turned out to be another issue, bpy.context.scene.view_settings.look output in current Blender is 'Medium Contrast' but the code checks for "Filmic - Medium Contrast", the same is true for all other looks except "None". Hope this information helps.

**Comment by macio97** [comment]
Problem solved.
